- .github/workflows/pypi-release.yml
Added a conditional statement that checks to see if the repository owner is "tsdat". If not, then the "Upload to TestPyPi" and "Upload to PyPi" steps will be skipped. 
Without this check the build and publish GitHub Action will always fail on forked repositories because the user will likely not have permissions to publish to the tsdat repo on pypi or test pypi servers (or, worse, they *will* have permission and then a package will be released from a source other than https://github.com/tsdat/tsdat).
It is useful to check that the package still *builds* correctly, so we only skip the release step instead of disabling the whole workflow on forked repos.
> Only run "Upload to PyPi" steps if running as tsdat

- tests/test_examples.py
- tsdat/pipeline/ingest_pipeline.py
- Fixes #18 
- Update `test_examples.py` to use the returned dataset from `IngestPipeline.run()`
> Make `IngestPipeline` return the output dataset

- docs/Makefile
- docs/source/tutorials/local_data_ingest.rst
The tutorial was broken ( #26 ). This PR addresses the following issues with it:
> Fix global marine ingest tutorial

- examples/a2e_buoy_ingest/config/storage_config.yml
- examples/a2e_imu_ingest/__init__.py
- examples/a2e_imu_ingest/config/storage_config.yml
- examples/a2e_imu_ingest/pipeline/__init__.py
- examples/a2e_imu_ingest/pipeline/handlers.py
- examples/a2e_lidar_ingest/__init__.py
- examples/a2e_lidar_ingest/config/storage_config.yml
- examples/a2e_lidar_ingest/pipeline/__init__.py
- examples/a2e_lidar_ingest/pipeline/handlers.py
- examples/a2e_waves_ingest/config/storage_config.yml
- tests/config/storage.yml
- tests/test_utils.py
- tsdat/__init__.py
- tsdat/io/__init__.py
- tsdat/io/filehandlers/__init__.py
- tsdat/io/handlers/__init__.py
- tsdat/io/handlers/csv.py
- tsdat/io/handlers/handlers.py
- tsdat/io/handlers/netcdf.py
- tsdat/io/storage.py
- tsdat/pipeline/ingest_pipeline.py
- tsdat/pipeline/pipeline.py
Rename `FileHandler` objects so as to start moving away from being strictly file-based.
> Rename `FileHandler` objects

- docs/source/collaboration.rst
- docs/source/index.rst
Our documentation did not include our email address or a link to our GitHub discussions page. We are including these now to expand our reach.
> Add ways to get in touch

- requirements.txt
The `act-atmos` v1.1.3 release includes a fix that makes adding qc variables much faster. This in turn fixes a `tsdat` performance issue when recording quality results for many data variables.
> Bump act-atmos version

- test/qc/test_qc.py
- tsdat/qc/handlers.py
The `RecordQualityResults` handler bit number was off by 1. The bit number is supposed to be 1-indexed, not 0-indexed.
> Fix `RecordQualityResults`

- requirements-dev.txt
- requirements.txt
Lighten requirements in core tsdat to reduce package size and reduce chances of errors occurring during installation.
> Lighten requirements

- .vscode/schema/pipeline-schema.json
- .vscode/schema/retriever-schema.json
- test/config/yaml/retriever.yaml
- tsdat/config/retriever.py
- tsdat/io/retrievers.py
Updated the `RetrieverConfig` to provide model information and schema validation for coords and data_vars. 
Also added a feature to drop the requirement that users specify a regex pattern for coordinate/data variable retrieval rules. To illustrate, in the screenshot below both the `time` coordinate and the `first` data_var will use the input variable name and data converters shown below for any input matching the regex pattern `.*`.
Fixes https://github.com/tsdat/pipeline-template/issues/13
> Expand `RetrieverConfig`, update schema

- docs/source/config/quality_control.rst
- docs/source/figures/pipeline.yaml
- test/qc/test_qc.py
- tsdat/qc/handlers.py
Rename the `ReplaceFailedValues` `QualityHandler` to its original name: `RemoveFailedValues`.
When this PR is merged a new release of tsdat should be done with an updated version to indicate breaking changes have occurred.
> Rename ReplaceFailedValues QualityHandler

- tsdat/utils/dsutils.py
The raw data should be allowed to have `NaT` timestamps, but currently the pipeline crashes because the `get_raw_start_time` method is unable to extract the starting timestamp on an array containing any `NaT` value. This PR fixes this bug by using `np.nanmin` instead of `np.min` to get the earliest timestamp from the data.
> Allow `NaT` values in raw data

- tests/test_utils.py
- tsdat/__init__.py
- tsdat/io/__init__.py
- tsdat/io/aws_storage.py
- tsdat/io/filehandlers/__init__.py
- tsdat/io/filehandlers/file_handlers.py
- tsdat/io/filesystem_storage.py
- tsdat/io/storage.py
- tsdat/pipeline/ingest_pipeline.py
- tsdat/pipeline/pipeline.py
This PR changes how the `DatastreamStorage` and `FileHandler` classes operate so that the data they contain is stored in *instances* of the class instead of as a class variable.
This fixes several headaches caused by tests failing in GitHub Actions but passing locally for the ingest-awaken repository, among others, due to how tests were being run. Now, regex patterns configured in the storage config file for internal file handlers will not clobber the file handlers registered for other ingests.
> Use instance variables for Storage and FileHandler

- .github/workflows/pytest.yml
- test/io/test_data_handlers.py
- test/io/test_storage.py
- tsdat/io/storage.py
Uses `pytest.mark.parametrize` to parametrize some tests and removes duplicate test trigger for github actions.
> Parametrize tests

- tsdat/pipeline/base.py
This PR fixes a bug where new variables were sometimes added to the dataset before new coordinate variables, causing the program to crash due to the unknown size/values of a coordinate dimension.
Using a list of coordinate, then variable names instead of a combined `set` of names preserves the addition order and resolves this issue.
> Add coords to dataset before data vars

- tsdat/pipeline/base.py
Bugfix for datatypes of variables listed in retriever and dataset config files are passed over in the retrieve config. Fixes #93
> Set retriever to assign variable datatypes

- test/qc/test_qc.py
- tsdat/qc/handlers.py
This PR adds support for passing a 'correction' config parameter to the `SortDatasetByCoordinate` quality handler, which is the previous behavior of tsdat
> Record SortDatasetByCoordinate corrections

- test/qc/test_qc.py
- tsdat/qc/checkers.py
- tsdat/qc/handlers.py
Closes #50 by adding useful debugging information to the `FailPipeline` QC handler error message.
Fixes #98 by passing the check with a warning for string data types.
Fixes #125 by using better dimension-agnostic logic for preserving shape after `np.diff`
> Fix quality check bugs, other qc improvements

- .vscode/schema/pipeline-schema.json
- docs/source/config/pipeline_config.rst
- tsdat/config/utils.py
This PR adds some documentation for config overrides to the readthedocs page and to the yaml validation schema.
> Add docs for config overrides

- test/io/test_data_handlers.py
- tsdat/io/writers.py
Replaces the current csv writer, which saves 1D variables but no metadata. This reader divides an xarray dataset into 2 files: a header file containing global attributes, a attributes file that contains variable metadata, a file containing 1D variables, and a file containing 2D variables. 2D variables are flattened into a coordinate list (x, y, var1, var2, ... varN) before saving.
> Expand CSV writer to save metadata and 2D variables

- requirements.txt
- tsdat/io/storage.py
This PR fixes a bug with the new `CSVWriter` where it writes additional metadata and csv data files adjacent to the path it is provided, but the FileSystemS3 class does not know to preserve these extra files.
> Allow FileSystemS3 to save multiple files

- tsdat/io/storage.py
With the recent custom storage path support we accidentally introduced a bug where the `FileSystemS3` class would crash upon instantiation due to an inherited validator in the `FileSystem` storage class. The validator can crash for S3 because it attempts to create a folder for the `storage_root` parameter. This PR includes a hack to disable that validator.
> Remove storage_root validator for FileSystemS3

- .github/workflows/pytest.yml
- pyproject.toml
- test/qc/test_qc.py
- tsdat/qc/checkers.py
- tsdat/qc/handlers.py
Update `CheckMonotonic` to be more robust at finding all bad timestamps, and update RemoveFailedValues to be able to drop coordinate values.
> Update QC Functions

- .github/workflows/pytest.yml
- .vscode/docstring.mustache
- .vscode/settings.json
- Makefile
- docs/source/config/hook_functions.rst
- docs/source/config/storage_config.rst
- docs/source/tutorials/data_ingest.rst
- test/config/test_pipeline_config.py
- test/config/yaml/pipeline.yaml
- test/io/test_data_handlers.py
- test/io/test_retrievers.py
- test/io/test_storage.py
- test/io/yaml/vap-storage.yaml
- test/pipeline/test_pipeline.py
- test/qc/test_qc.py
- test/test_tstring.py
- tsdat/io/base.py
- tsdat/io/handlers.py
- tsdat/io/retrievers.py
- tsdat/io/storage.py
- tsdat/io/writers.py
- tsdat/qc/base.py
- tsdat/qc/checkers.py
- tsdat/transform/converters.py
- tsdat/tstring.py
- tsdat/utils.py
Semi-large refactor of the storage classes to better support custom storage paths and naming conventions.
Previously the FileSystem storage class assumed that files would be named like `datastream.start.end.ext`, where `datastream` was always `location.name-qual-temp.level`, but also allowed users to provide their own `datastream` as a global attribute which could be used instead. If a custom `datastream` was set (such as those used by A2e), the `FileSystem` storage classes would try and fail to parse out the location, name, qualifier, temporal, and data level attributes from the datastream, causing the whole pipeline to crash.
Now, an optional metadata dictionary can be passed to various methods that previously relied on parsing fields from the `datastream`. This means we can use storage …
> Refactor storage classes, fix QC

- docs/source/config/hook_functions.rst
- docs/source/tutorials/data_ingest.rst
- test/config/test_pipeline_config.py
- test/config/yaml/pipeline.yaml
- test/pipeline/examples.py
- test/pipeline/test_pipeline.py
- tsdat/pipeline/pipelines.py
This PR adds a `IngestPipeline.get_ancillary_filepath` convenience function that wraps the `IngestPipeline.storage.get_ancillary_filepath` function, providing all the default arguments except for the title.
Now this is valid:
```python
filepath = self.get_ancillary_filepath("wind_speed")
fig.savefig(filepath)
```
Previously this was necessary:
```python
with self.storage.uploadable_dir() as tmp_dir:
filepath = self.get_ancillary_filepath(title="wind_speed", dataset=dataset, root_dir=tmp_dir)
fig.savefig(filepath)
```
Closes #147
> Ancillary filepath

- tsdat/io/writers.py
Using `"str"` instead of "S1" for the datatype fixes the `string1` dimension problem for string variables. Also removed compression encoding for string variables to fix `NetCDF: Filter error: bad id or parameters or duplicate filter` error, which was a regression from NetCDF4 1.5.8.
> Fix encoding for string data

- test/config/test_dataset_config.py
- test/io/test_data_handlers.py
- test/qc/test_qc.py
- tsdat/config/attributes.py
- tsdat/config/utils.py
- tsdat/config/variables.py
- tsdat/io/base.py
- tsdat/io/writers.py
- tsdat/qc/handlers.py
- tsdat/transform/adi.py
This PR replaces all `warnings.warn` calls with `logger.warning` to help improve how logs are captured downstream.
> Improve logging for warnings

- test/pipeline/test_pipeline.py
- tsdat/pipeline/pipelines.py
This PR adds an `inputs` global attribute, which for `IngestPipelines` records the files used as input to an ingest. For `TransformationPipelines`, this records the `datastream::start::end` keys used.
> Record pipeline inputs

- tsdat/pipeline/base.py
This is an issue that Bridget has brought up in WFIP3 data reviews. "Created by..." is the same phrasing ARM uses and reads nicer than "Ran by..."
> Say "Created by..." in the history global attribute

- test/adi/test_transform.py
- test/config/yaml/dataset.yaml
- test/io/test_converters.py
- test/test_main.py
- tsdat/config/variables/ureg.py
- tsdat/config/variables/variable_attributes.py
- tsdat/io/converters/units_converter.py
Fix for issue #177
- Will take correct CF version of temperature units 
- Will take units that don't include exponent symbols (i.e. m s-1 instead of m/s)
- Removed requirement for units attribute - if no units are supplied, the variable is assumed dimensionless
- Will now allow ability to convert dimensionless unit ("unitless", "", or None) to percent ("percent" or "%") (i.e 1.0 -> 100%)
> Defined units

- test/io/test_storage.py
- test/test_tstring.py
- tsdat/const/const.py
- tsdat/io/base/storage.py
- tsdat/io/storage/file_system.py
- tsdat/io/storage/file_system_s3.py
- tsdat/tstring.py
- tsdat/utils/datetime_substitutions.py
- tsdat/utils/get_filename.py
This PR makes some changes to the `tstring` and `io.storage` submodules to improve how robustly `tsdat` is able to find files matching the filepath template.
Notable changes include:
* Using `allow_missing=True` in `tstring.Template.substitute` will now no longer remove the unsubstituted components (e.g., `Template("{a}.{b}[.{c}]").substitute(a="1", allow_missing=True) --> "1.{b}[.{c}]"`). 
* In `FileSystem`/`FileSystemS3` filepath templates: using `fill='*'` sometimes resulted in invalid glob patterns due to repeated `*` characters. This has been fixed.
* Added `{yyyy}`, `{mm}`, `{dd}`, `{HH}`, `{MM}`, and `{SS}` datetime substitutions.
> Improve template strings

- pyproject.toml
- tsdat/qc/checkers/oceanography/check_goring_nikora_2002.py
- tsdat/qc/handlers/cubic_spline_interp.py
This PR adds some dependency classifiers so users don't need to install all possible `tsdat` dependencies in order to use the library. The new classifiers are:
* `tsdat[aws]`: Installs `boto3`
* `tsdat[io]`: Installs `h5netcdf`, `pyarrow`, and `zarr`. Note that `netcdf4` is still included in `tsdat` by default.
* `tsdat[ocean]`: Installs `mhkit`, as used by `CheckGoringNikora2002` and `CubicSplineInterp`
There is also `tsdat[complete]` which installs all of the above, and `tsdat[dev]` which installs all of the above and some additional libraries used for testing and development of `tsdat`.
closes #95
> Optional dependencies

- tsdat/pipeline/pipelines/ingest_pipeline.py
- tsdat/pipeline/pipelines/transformation_pipeline.py
code hooks shouldn't have been converted into staticmethods in a recent refactor. My bad. This should fix it.
> Revert pipeline code hook signatures

- test/io/test_retrievers.py
- tsdat/io/base/retrieved_variable.py
- tsdat/io/converters/units_converter.py
This PR adds a `UnitsConverter` to the list of `data_converters` for every retrieved variable, if it doesn't already define a `UnitsConverter`. The new `UnitsConverter` will attempt to automatically detect the input units from the input dataset (`variable.attrs.get("units")`). If no units are found, or if the units are `"1"`, then the conversion is skipped.
> Add UnitsConverter automatically

- test/config/test_pipeline_config.py
- test/config/yaml/invalid-pipeline.yaml
- test/config/yaml/pipeline.yaml
- tsdat/config/pipeline/pipeline_config.py
- tsdat/config/utils/__init__.py
- tsdat/config/utils/matches_overridable_schema.py
- tsdat/pipeline/base/pipeline.py
This PR allows relative paths in pipeline config files. See #174 for more details, but the gist is that this is now doable (and recommended, since it is more readable):
**`pipelines/example/config/pipeline.yaml`**
```yaml
classname: pipelines.example.pipeline.Ingest
triggers: ['.*\.csv']
retriever:
path: ./retriever.yaml  # --> pipelines/example/config/retriever.yaml
dataset:
path: ./dataset.yaml  # --> pipelines/example/config/dataset.yaml
quality:
path: ../config/quality.yaml  # --> pipelines/example/config/quality.yaml
storage:
path: shared/storage.yaml  # can also use the same paths as before
```
> Allow relative paths in config files

- pyproject.toml
`Mhkit` attempts to parse the version numbers from matplotlib, but fails for the current latest release of matplotlib (`3.9.1.post1`) because the `.post1` suffix can't be converted to a number using `int()`. This PR just installs a different version of matplotlib if tsdat is installed using the `tsdat[ocean]` qualifier to get around this.
> Fix matplotlib version for mhkit

- docs/config/dataset_config.md
- docs/config/pipeline_config.md
- docs/config/retriever_config.md
- test/io/test_a2e_csv.py
Add documentation for dataset.yaml (Sample Configuration of Dataset.yaml) abd retriever.yaml (Section for Coords and Data_vars)
Task: 
The developer guide --> dataset config page should contain an annotated example of a dataset config file
The retriever configuration in the developer guide only covers readers and converters. It should also cover the settings for coords and data_vars
> Add documentation 

- tsdat/config/variables/ureg.py
Adds support for Volt Ampere Reactive (var / VAR) units, used in the power industry.
>  Define kVAR units

- pyproject.toml
Adi_py and the other ARM conda packages that support time-series transformations in tsdat are currently incompatible with numpy 2.0+. This PR adds a new optional dependency classifier "transform" which limits numpy to <2.0.0. The "transform" classifier is included by default in `pip install tsdat[complete]`
> Limit numpy version due to adi_py dependency
