tsdat/tsdat

.gitignore, test/config/test_dataset_config.py, test/config/yaml/dataset.yaml, test/config/yaml/quality.yaml, test/config/yaml/retriever.yaml, test/io/test_retrievers.py, test/pipeline/test_pipeline.py, test/utils.py, tsdat/config/pipeline.py, tsdat/config/utils.py, tsdat/config/variables.py, tsdat/io/converters.py, tsdat/io/writers.py, tsdat/pipeline/dispatcher.py, tsdat/pipeline/ingest.py, tsdat/pipeline/pipeline.py, tsdat/qc/checkers.py, tsdat/qc/handlers.py, tsdat/qc/qc.py, tsdat/utils.py
Added initialization of derived variables to output dataset
Added variable and global attributes to output dataset
Move decode_cf hack into NetCDFWriter
Fix and test recusive instantiation mechanism
Add FailPipeline QC Handler
Add py.typed file
=> Implement IngestPipeline

test/qc/test_qc.py, tsdat/qc/checkers.py, tsdat/qc/handlers.py
- Added `CheckMin`/`CheckMax` suite of `QualityCheckers`
- Added `CheckDelta` suite of `QualityCheckers`
- Added `RecordQualityResults`, `ReplaceFailedValues`, and `SortDatasetByCoordinate` `QualityHandlers`
- Added tests for added `QualityCheckers`
- Added tests for added `QualityHandlers`
=> Add QC Checkers and Handlers

setup.py, tsdat/__init__.py, tsdat/__main__.py, tsdat/config/utils.py, tsdat/main.py
Bundle console scripts into the setup. Currently this includes only the typer CLI to generate json schema, but also makes it easier to add more scripts later.
=> Add console scripts

docs/source/_static/css/custom.css, docs/source/conf.py, tsdat/config/dataset.py, tsdat/config/pipeline.py, tsdat/config/quality.py, tsdat/config/retriever.py, tsdat/config/storage.py, tsdat/config/utils.py, tsdat/io/base.py, tsdat/io/converters.py, tsdat/io/retrievers.py, tsdat/io/storage.py, tsdat/pipeline/pipelines.py, tsdat/qc/base.py, tsdat/qc/checkers.py, tsdat/testing.py, tsdat/utils.py
=> Update API docs

test/test_main.py, tsdat/__main__.py
=> Test schema generator cli

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Clean up issue templates

MANIFEST.in
Remove unused `MANIFEST.in` file
=> Remove `MANIFEST.in`

.github/workflows/pytest.yml
Add Python 3.10 to the test suite
=> Support 3.10

tsdat/qc/handlers.py
=> Solution for `ReplaceFailedValues` Bug

requirements-dev.txt, test/io/test_storage.py, tsdat/io/storage.py
This PR mocks the connection to AWS to make testing easier, faster, and more reliable.
=> Mock aws connection

tsdat/io/retrievers.py
Workaround for an issue with non-dimensional coordinates in input datasets
=> Retrieve zero-dim coordinates

.vscode/schema/dataset-schema.json, .vscode/schema/pipeline-schema.json, test/config/test_dataset_config.py, tsdat/config/attributes.py
Loosens attribute validation on location_id and qualifier so that either can be less than 3 characters.
=> Loosen attribute validation

.vscode/schema/retriever-schema.json, test/config/yaml/retriever.yaml, tsdat/config/retriever.py, tsdat/io/base.py, tsdat/io/retrievers.py
Allow list of multiple names to retriever (Fix for #129)
=> Retriever names

docs/source/config/storage_config.rst, requirements.txt, test/config/test_storage_config.py, test/config/yaml/dataset.yaml, test/config/yaml/storage.yaml, test/io/test_storage.py, tsdat/config/attributes.py, tsdat/io/storage.py, tsdat/utils.py
This PR adds support for customizing the output directory structure via the storage configuration file without any breaking changes.
Tasks:
Co-authored-by: James McVey <53623232+jmcvey3@users.noreply.github.com>
=> Custom storage paths

test/io/test_data_handlers.py, tsdat/io/writers.py
With the changes from William. Made some updates to the testing to accommodate changes to the saved files.
=> Update csv writer

pyproject.toml, tsdat/io/writers.py
Improvements for string compression in the NetCDF and SplitNetCDF writer classes.
=> Improve netcdf string compression

.readthedocs.yml, docs/source/conf.py, pyproject.toml
This PR fixes the build errors for the documentation on readthedocs.
=> Fix docs build errors

.github/workflows/pypi-release.yml, .github/workflows/pytest.yml, environment.yml, test/io/test_retrievers.py, test/io/yaml/vap-retriever-fetch.yaml
=> Revert "Update actions"

tsdat/const/__init__.py, tsdat/const/const.py, tsdat/transform/adi/__init__.py, tsdat/transform/adi/adi_alignments.py, tsdat/transform/adi/adi_qc_atts.py, tsdat/transform/adi/adi_transformation_types.py, tsdat/transform/adi/adi_transformer.py, tsdat/transform/adi/bad_transformation_settings_error.py, tsdat/transform/adi/transform_parameter_converter.py, tsdat/transform/converters/__init__.py, tsdat/transform/converters/_adi_base_transformer.py, tsdat/transform/converters/_create_bounds.py, tsdat/transform/converters/automatic.py, tsdat/transform/converters/bin_average.py, tsdat/transform/converters/create_time_grid.py, tsdat/transform/converters/error_traceback.py, tsdat/transform/converters/interpolate.py, tsdat/transform/converters/nearest_neighbor.py
Refactored all of the transform files to the new multi-file format.
Note: The unit tests are failing for the same reason the tests in #187 are. Once that's resolved, and if tests pass afterward, I'll move this out of draft state.
=> Transform refactor

docs/config/pipeline_config.md, docs/tutorials/data_ingest.md, docs/tutorials/vap_pipelines.md, test/config/test_dataset_config.py, test/config/yaml/dataset.yaml, test/io/test_data_handlers.py, test/io/test_retrievers.py, test/io/yaml/vap-dataset-2D.yaml, test/io/yaml/vap-dataset-transform.yaml, test/io/yaml/vap-dataset.yaml, test/io/yaml/vap-retriever-transform.yaml, tsdat/io/writers/csv_writer.py, tsdat/transform/converters/create_time_grid.py
This PR fixes some of the warnings that show up when testing tsdat.
=> Fix runtime/test warnings

test/qc/test_check_outliers.py, tsdat/qc/checkers/__init__.py, tsdat/qc/checkers/check_outliers.py
This PR fixes a crucial typo in the `CheckOutliers` quality checker and adds tests to make sure this doesn't happen again.
=> Fix `CheckOutliers`

test/utils/test_get_filename.py, tsdat/utils/get_filename.py
=> Fix `get_filename()` improper `"title"` substitution

test/io/test_retrievers.py, tsdat/io/retrievers/storage_retriever.py
=> Don't send empty variables through adi_py

docs/config/dataset_config.md
closes https://github.com/tsdat/tsdat/issues/226
=> add link to udunits2

test/io/test_converters.py, tsdat/config/variables/ureg.py, tsdat/io/converters/units_converter.py
This PR includes some changes to the units converter that allow it to function better when the input or output units are missing or invalid.
=> Handle missing units better

tsdat/io/storage/file_system.py
This PR makes the `fetch_data` method of `FileSystem(Storage)` class significantly faster when there are multiple files to fetch by using `xr.concat` instead of `xr.merge`.
=> Make `fetch_data` method faster for FileSystem storage
